### PR TITLE
Only add needed user when filtering by `--author`

### LINKED ISSUE #67: Don't append all authors to WXR if `author` arg provided
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

When exporting content with the `author` arg set the export contains _all_ the authors still. My use case is that I would like to export data per user in order to send that export over to them - I'm decommissioning a site and want to provide people the opportunity to reuse that information.
 
I want to do this without leaking the personal data of other users.

**Describe the solution you'd like**

If the `author` arg is passed to the command don't prepend all authors to each WXR file. There only needs to be a single author.

### PR DESCRIPTION
**Pull request by schlessera**
Instead of adding all users unconditionally, only add the one user that is needed when filtering by a specific `--author`.

Fixes #67

### CODE REVIEW

**Comment by pjv** [comment]
@schlessera I’m not sure if I am understanding correctly what this patch is supposed to do, or if I am using the export cli command correctly, but if I do and I am, then this patch doesn’t seem to be doing what I think it should be doing.

Here’s my steps and my results:

1. I updated wp cli on my test site to 2.5.0
2. I installed the latest master version of export-command over that by doing `wp package install git@github.com:wp-cli/export-command.git`
3. I tested the resulting output by exporting a single page from the test site where that page is the only page authored by a specific author using a command like so `wp export --post_type=page --author=<my-userid> --skip_comments --stdout > page.xml`

The resulting file (page.xml) has thousands of `<wp:author>` items in it. I expected that it would only have the one for `my-userid`.

Am I misunderstanding this patch or doing something wrong?

**Comment by pjv** [comment]
Hello @schlessera ^^

**Comment by schlessera** [comment]
@pjv This patch is not part of the v2.5.0 release. To test it, you'll need to use the latest nightly version of WP-CLI. You can update to the latest nightly version with the following command:
```bash
wp cli update --nightly
```

**Comment by pjv** [comment]
@schlessera Thank you, but shouldn't doing this:

`wp package install git@github.com:wp-cli/export-command.git`

override the built-in wp cli export command with the current master branch of this repo?

**Pull request merged**
